site_name: InterpolatePy
site_description: "A comprehensive Python library for trajectory planning and curve interpolation."

repo_url: https://github.com/GiorgioMedico/InterpolatePy
repo_name: GiorgioMedico/InterpolatePy

theme:
  icon:
    repo: fontawesome/brands/github
  name: "material"
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: "blue"
      accent: "grey"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: "blue"
      accent: "white"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - "Home": index.md
  - "API Reference": api.md
